name: comnow
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  responsive_sizer: ^3.2.0
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  pin_code_fields: ^8.0.1
  fluttertoast: ^8.2.4
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  share_plus: ^7.2.1
  connectivity_plus: ^5.0.2
  http: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/png/


  fonts:
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Roboto-Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
