import 'dart:ui';

class CustomColors {
  static const Color topBackgroundColor = Color(0xFF121212);
  static const Color bottomBackgroundColor = Color(0xFF1E1F1D);
  static const Color topButtonColor = Color(0xFF696969);
  static const Color bottomButtonColor = Color(0xFF0A0A0A);
  static const Color titleWhiteTextColor = Color(0xFFFFFFFF);
  static const Color titleBlackTextColor = Color(0xFF050505);
  static const Color whiteButtonColor = Color(0xFFFFFFFF);
  static const Color blueButtonColor = Color(0xFF0E9AFF);
  static const Color selectUserCardBackgroundColor = Color(0xFFFFFFFF);
  static const Color textFormFieldBackgroundColor = Color(0xFF3A3A3A);
  static const Color hintColor = Color(0xFFC1C1C1);
  static const Color blueTextColor = Color(0xFF0E9AFF);
  static const Color textFormFieldHintColor = Color(0xFFC1C1C1);
  static const Color tabBarColor = Color(0xFF1B1B1B);
  static const Color tabBarTextColor = Color(0xFF7D7D7D);
  static const Color activeTabBarColor = Color(0xFFF5F5F5);
  static const Color dialogBoxColor = Color(0xFF292929);
  static const Color popupMenuColor = Color(0xFF292929);
  static const Color toastColor = Color(0xFF464646);
  static const Color acceptColor = Color(0xFFAF2C2D);
  static const Color declineColor = Color(0xFFD2BD07);
  static const Color pendingColor = Color(0xFF1E7409);
  static const Color voiceNoteColor = Color(0xFF969696);
  static const Color redColor = Color(0xFFEA2A2A);
  static const Color orangeColor = Color(0xFFE4951F);
  static const Color yellowColor = Color(0xFFE4DC1F);
  static const Color greenColor = Color(0xFF46E41F);
  static const Color skyBlueColor = Color(0xFF1FE4C1);
  static const Color blueColor = Color(0xFF218FF5);
  static const Color darkBlueColor = Color(0xFF2F1FE4);
  static const Color purpleColor = Color(0xFFC81FE4);
  static const Color pinkColor = Color(0xFFE41FA1);
  static const Color leftMemberBGColor = Color(0xFFC3C3C3);
  static const Color leftMemberBGCardColor = Color(0xFF858585);
  static const Color lightGreenCardColor = Color(0xFFADE903);
  static const Color settingTitleBGColor = Color(0xFF4E4E4E);
}
